### ISSUE TITLE
Create new release to reflect fixed license string

### ISSUE THREAD

**Issue by matthewbeckler** [dominictarr/pause-stream#10]
It would be nice to push a new version to NPM that includes the fixed version string. Thanks!

**Comment by dominictarr** [comment]
sorry, I no longer have publish rights so I can't.
https://www.npmjs.com/package/pause-stream
(it now belongs to "nopersonsmodules")
you'll have to fork it to a new name

**Comment by matthewbeckler** [comment]
Ok thanks! Dealing with some ancient code here, and will probably migrate away from this package. Thanks again!
